package com.aiwujie.shengmo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.aiwujie.shengmo.bean.SwitchMarkBean;

import com.aiwujie.shengmo.dao.SwitchMarkBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig switchMarkBeanDaoConfig;

    private final SwitchMarkBeanDao switchMarkBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        switchMarkBeanDaoConfig = daoConfigMap.get(SwitchMarkBeanDao.class).clone();
        switchMarkBeanDaoConfig.initIdentityScope(type);

        switchMarkBeanDao = new SwitchMarkBeanDao(switchMarkBeanDaoConfig, this);

        registerDao(SwitchMarkBean.class, switchMarkBeanDao);
    }
    
    public void clear() {
        switchMarkBeanDaoConfig.clearIdentityScope();
    }

    public SwitchMarkBeanDao getSwitchMarkBeanDao() {
        return switchMarkBeanDao;
    }

}
